package commands

import (
	"testing"

	"github.com/spf13/cobra"
)

// TestEveryLeafCommandHasRunner verifies that every single command in the CLI
// tree that does not have subcommands has either a Run or RunE function.
// This prevents commands from silently dumping help text instead of executing.
func TestEveryLeafCommandHasRunner(t *testing.T) {
	// Root command is rootCmd
	checkCommand(t, rootCmd)
}

func checkCommand(t *testing.T, cmd *cobra.Command) {
	subcommands := cmd.Commands()

	// If this is a leaf command (no subcommands), it MUST have Run or RunE
	// (except the built-in "help" and "completion" commands generated by Cobra).
	if len(subcommands) == 0 {
		if cmd.Name() == "help" {
			return
		}
		if cmd.Run == nil && cmd.RunE == nil {
			t.Errorf("FAIL: Leaf command %q has NO Run or RunE handler!", cmd.CommandPath())
		} else {
			t.Logf("OK: %q (leaf, has handler)", cmd.CommandPath())
		}
		return
	}

	t.Logf("PARENT: %q (%d subcommands)", cmd.CommandPath(), len(subcommands))
	for _, sub := range subcommands {
		checkCommand(t, sub)
	}
}
